name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: heliannuuthus/hephaestus/.github/workflows/ci-deploy-pages.yml@main
    with:
      workdir: ./
      build: build:docs
      artifact-path: apps/docs/dist
